language: perl
perl:
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"

matrix:
   include:
      - perl: "5.17.10"
        env:
           - BREWVER="5.17.10"
   allow_failures:
      - perl: "5.17.10"

#notifications:
  #irc:
    #channels:
      #- "irc.perl.org#catalyst-dev"

before_install:
    - test "$BREWVER" = "" || perlbrew install -j4 $BREWVER
    - test "$BREWVER" = "" || perlbrew switch $BREWVER
    - test "$BREWVER" = "" || perl -v

install:
   # git bits sometimes needed...
   - git config user.name 'Travis-CI'
   - git config user.email 'travis@nowhere.dne'

   # ensure we have the latest cpanm
   - echo y | perlbrew install-cpanm

   # XML cpan deps
   - apt-get -yinstall libexpat-dev

   # see if we can't speed things up a bit
   - rm -rf ~/.cpanm
   - mkdir ~/.cpanm
   - sudo mount tmpfs -t tmpfs ~/.cpanm

   # these fail on parallel test runs
   #    Net::Server:  https://rt.cpan.org/Ticket/Display.html?id=84126
   - cpanm --metacpan --skip-satisfied Net::Server Template File::Remove Filesys::Notify::Simple Config::Any CGI::Simple Plack

   # for testing
   - cpanm --metacpan --skip-satisfied YAML

   # enable various test options, including parallel testing
   - export AUTOMATED_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1

   # M::I deps
   - cpanm --metacpan --skip-satisfied Module::Install Module::Install::AuthorRequires Module::Install::CheckConflicts Module::Install::AuthorTests Module::Install::Authority

   # author deps -- wish there was a better way
   #- cpanm --metacpan --skip-satisfied CatalystX::LeakChecker Catalyst::Devel Catalyst::Engine::PSGI Starman MooseX::Daemonize
   - cpanm --metacpan --skip-satisfied Module::Info File::Find::Rule Test::Pod Test::Pod::Coverage Test::Spelling Pod::Coverage::TrustPod || cat /home/travis/.cpanm/build.log
   - cpanm --metacpan --skip-satisfied JSON JSON::XS Data::Taxi Config::General PHP::Serialization FreezeThaw XML::Simple || cat /home/travis/.cpanm/build.log
   - cpanm --metacpan --skip-satisfied --installdeps . || cat /home/travis/.cpanm/build.log

   # we want these for our tests, but not for any others
   - export AUTHOR_TESTING=1
   - export RELEASE_TESTING=1

   - make manifest

script:
   - make disttest
